Remove use of unsupported progmem typedefs
Newer AVR-GCC versions used in recent versions of the Arduino IDE no
longer support the use of the non-standard progmem typedefs, causing
compilation to fail without this change:
```
E:\arduino\libraries\FastSerial\BetterStream.cpp:20:29: error:
'prog_char' does not name a type
```
```
E:\arduino\libraries\FastSerial\vprintf.cpp:55:40: error: 'prog_char'
does not name a type
```