Force Arduino HardwareSerial library to be included after FastSerial library
Recent Arduino IDE versions have changed the sketch preprocessing system
which causes the automatically added include of Arduino.h to be added
before the FastSerial include. FastSerial relies on being called before
Arduino.h and so without this change trying to compile ArduinoMavLink
with any recent IDE version fails with the error:
```
E:\arduino\libraries\FastSerial/FastSerial.h:47:3: error: #error Must
include FastSerial.h before the Arduino serial driver is defined.
```